rg.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
neo_version_range=[21.1.250,)
loader_version_range=[4,)

jei_version=19.25.0.322
geckolib_version=4.9.3

mod_id=sculkhorde
mod_name=Sculk Horde
mod_license=Apache 2.0
mod_version=1.21.1-1.0.0
mod_group_id=com.github.sculkhorde
mod_authors=Team Peril
