modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="sculkhorde.png"
credits="Wolfieboy09, DaPlumer"
authors="Team Peril"
description='''
Sculk Horde implements a new end-game era to your game that once activated, will force you to fight against the newly awoken ancient sculk horde in order to survive. This ancient enemy seeks to infect and consume the world in its entirety.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[${geckolib_version},)"
ordering="NONE"
side="BOTH"
